### ISSUE TITLE
Forcing HTTPS at a webserver for this script is not beneficial

### ISSUE THREAD

**Issue by Manuel1948** [SlenkyDev/StopRussia.net.ua#21]
If you host apage with this script like on stoprussia.net.ua and forces a redirect to HTTPS, the browser blocks every request to HTTP content. And if you check the links, the URLs of Kremlin are HTTP.

Only for your interest and others.

**Comment by SlenkyDev** [comment]
Will take a look at it tomorrow, it's a Cloudflare setting.

**Comment by Manuel1948** [comment]
it is still redirecting to HTTPS

**Comment by SlenkyDev** [comment]
> it is still redirecting to HTTPS

Fixed

**Comment by Manuel1948** [comment]
> > it is still redirecting to HTTPS
> 
> Fixed

It's not fixed, check it by yourself: https://www.redirect-checker.org/index.php
